apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_GaRZLWC4K7sg@ep-ancient-pond-a11noqd2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"