apiVersion: v1
kind: Service
metadata:
  name: simulator-backend
  namespace: simulator
spec:
  type: LoadBalancer
  selector:
    app: simulator-backend
  ports:
    - name: http
      port: 80
      targetPort: 4000

